# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Darin Self
email:
description:  Website for Darin Sanders Self
twitter_username: darinself
github_username: dsself
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Darin Sanders Self"
  avatar : "/assets/images/headshot4.jpg"
  bio    : "Assistant Professor <br/>
            Department of Political Science <br/>
            Brigham Young Univeristy"
  location: Provo, UT
  links:
    - label: "Student Hours"
      icon: <i class="fa-solid fa-backpack"></i>
      url: "https://calendly.com/darinself"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/darinself"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dsself"
    - label: "Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=YJWrC5APERQC&hl"
    # -label: "Research Gate"
    #  icon: "fab fa-fw fa-registered"
    #  url: "https://www.researchgate.net/profile/Darin_Self"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:darin_self@byu.edu"


#footer:
 # links:
  #  - label: "Twitter"
   #   icon: "fab fa-fw fa-twitter-square"
    #  url: "https://twitter.com/"
    #- label: "GitHub"
    #  icon: "fab fa-fw fa-github"
    #  url: "https://github.com/"


defaults:
  # _posts
  - scope:
      path: ""
      #type: posts
    values:
      layout: archive
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: archives
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
